add alpine arm version
treehouses/moodole pull request #15
Opened 2017-12-05 16:26 UTC by Dashlorde

2017-12-05 18:35 UTC, mappuji commented on 3.4/arm_alpine/Dockerfile
> +RUN wget -O /var/www/moodle-${version}.tar.gz https://github.com/moodle/moodle/archive/v${version}.tar.gz && \
could you delete the artifact after extraction?

2017-12-05 18:35 UTC, mappuji commented on 3.4/arm_alpine/config/php.ini
> +[PHP]
Can you minify this by delete comment?

2017-12-05 18:36 UTC, mappuji commented on 3.4/arm_alpine/docker-compose.yml
> +    - POSTGRES_DATABASE=moodle
Put comment here like https://github.com/ole-vi/moodole/pull/16

2017-12-05 18:36 UTC, mappuji commented on 3.4/arm_alpine/docker-compose.yml
> +    - MOODLE_URL=http://docker.ole.org:80
We have new convention see https://github.com/ole-vi/moodole/pull/16 and add also config like this https://github.com/ole-vi/moodole/blob/e65dd944d14e26a802364bfab8131a77af8e2623/3.4/x86/config.php

2017-12-05 18:38 UTC, empeje requested changes
Need some changes, due to use case requirement

* Need to access site from different way
  - IP
  - Domain
  - local
  - Tunnel

follow convention written here https://github.com/ole-vi/moodole/pull/16

@Dashlorde how many MB the resulted image would be?

2017-12-23 10:11 UTC, mappuji commented
Please adapt with this changes https://github.com/ole-vi/moodole/pull/26

2018-01-24 06:19 UTC, mappuji commented
Congrats @Dashlorde ! Will test it soon.

2018-01-24 21:21 UTC, empeje requested changes
found it  @Dashlorde 

```
bash: line 80: deploy_arm_alpine: command not found
```
https://api.travis-ci.org/v3/job/332958913/log.txt

seems typo here
https://github.com/treehouses/moodole/blob/6bea83655a2765e0ccfbd93233f571095e9a43ea/.travis/travis_utils.sh#L126

2018-01-24 21:36 UTC, Dashlorde commented
typo fixed @mappuji

2018-01-25 03:10 UTC, mappuji commented
Thanks @Dashlorde , last step is to test it.

2018-01-25 06:36 UTC, Dashlorde commented
hi @mappuji I am running moodle at docker.ole.org

2018-01-25 11:31 UTC, mappuji commented
hello @Dashlorde currently checking it

2018-01-25 11:32 UTC, mappuji commented
Can you also update README to include how to use alpine version?

2018-01-25 13:26 UTC, mappuji commented
Done, will merge it.

2018-01-25 13:27 UTC, merged